# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91282f38289fca8137cb4b45bc4d8a9f04d2d805726df61a8f40634987d0320fe140746bff043dd0b993a9d47c8338843328b5a730fb5cddd62c8363191be921

test:
  secret_key_base: 8bf24b7a077e7e0110f36590a20b6c05adfb9a15f4a4def57caf616530c445380486742438a2951b6fef74ae4593a365c4f06e3adbcc44f72ae79b6b36514e3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
